AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  minty
  
  Sample SAM Template for minty

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  MintyRecieverFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/minty/
      Handler: minty
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          ACCESS_KEY: ""
          SECRET_KEY: ""
          REGION: "us-east-1"
          SLACK_CHANNEL: ""
          NOTIFICATION_TYPE: "slack"
          BUCKET_NAME: ""
          KEY_PREFIX: ""
          SLACK_API_URL: ""

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MintyRecieverFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt MintyRecieverFunction.Arn
  MintyRecieverFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt MintyRecieverFunctionRole.Arn
